# Generated by Django 3.2.6 on 2021-08-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
